## capture-agent-common/vars
---
host_ip_address: "{{ '127.0.0.1' if ip_address == 'dhcp' else ip_address }}"

logfile: "{{ GC_log_path }}"

ca_hostname: "{{ ansible_custom_hostname }}"
ip_address: "{{ ansible_release_host|default('dhcp') }}"
